-- Enable the pgvector extension to work with embedding vectors
create extension if not exists vector;

-- Users table
create table public.users (
  telegram_user_id bigint not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  username text null,
  first_name text null,
  last_name text null,
  constraint users_pkey primary key (telegram_user_id)
) TABLESPACE pg_default;

-- Projects table
create table public.projects (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  title text not null,
  summary text null,
  telegram_message_id bigint not null,
  telegram_chat_id bigint not null,
  user_id bigint null,
  status text null default 'active'::text,
  feedback_summary text null,
  constraint projects_pkey primary key (id),
  constraint projects_user_id_fkey foreign KEY (user_id) references users (telegram_user_id),
  constraint projects_status_check check (
    (
      status = any (array['active'::text, 'archived'::text])
    )
  )
) TABLESPACE pg_default;

create index IF not exists projects_telegram_message_id_idx on public.projects using btree (telegram_message_id) TABLESPACE pg_default;

create index IF not exists projects_user_id_idx on public.projects using btree (user_id) TABLESPACE pg_default;

-- Feedback table
create table public.feedback (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  project_id bigint null,
  user_id bigint null,
  content text null,
  message_id bigint not null,
  parent_message_id bigint null,
  media_url text null,
  media_type text null,
  score_relevance integer null,
  score_depth integer null,
  score_evidence integer null,
  score_constructiveness integer null,
  score_tone integer null,
  constraint feedback_pkey primary key (id),
  constraint feedback_project_id_fkey foreign KEY (project_id) references projects (id) on delete CASCADE,
  constraint feedback_user_id_fkey foreign KEY (user_id) references users (telegram_user_id)
) TABLESPACE pg_default;

create index IF not exists feedback_project_id_idx on public.feedback using btree (project_id) TABLESPACE pg_default;

create index IF not exists feedback_user_id_idx on public.feedback using btree (user_id) TABLESPACE pg_default;