-- Enable the pgvector extension to work with embedding vectors
create extension if not exists vector;

-- Users table
create table users (
  telegram_user_id bigint primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  username text,
  first_name text,
  last_name text
);

-- Projects table
create table projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  summary text,
  telegram_message_id bigint not null, -- The ID of the root message in Telegram
  telegram_chat_id bigint not null, -- The ID of the chat where the project was posted
  user_id bigint references users(telegram_user_id), -- Creator of the project
  status text default 'active' check (status in ('active', 'archived'))
);

-- Feedback table
create table feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  project_id bigint references projects(id) on delete cascade,
  user_id bigint references users(telegram_user_id), -- Telegram User ID
  content text,
  message_id bigint not null, -- Telegram Message ID of the feedback
  parent_message_id bigint, -- If it's a reply to another feedback
  media_url text, -- URL to image/video/doc if any
  media_type text, -- 'photo', 'video', 'document', etc.
  
  -- AI Scoring
  score_relevance int,
  score_depth int,
  score_evidence int,
  score_constructiveness int,
  score_tone int,
  ai_summary text
);

-- Indexes for faster search
create index projects_telegram_message_id_idx on projects(telegram_message_id);
create index feedback_project_id_idx on feedback(project_id);
create index projects_user_id_idx on projects(user_id);
create index feedback_user_id_idx on feedback(user_id);
