-- Enable the pgvector extension to work with embedding vectors
create extension if not exists vector;

-- Users table
create table public.users (
  id bigint generated by default as identity not null,
  telegram_user_id bigint null,
  wallet_address text null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  username text null,
  first_name text null,
  last_name text null,
  xp integer not null default 0,
  tier text not null default 'bronze'::text,
  constraint users_pkey primary key (id),
  constraint users_wallet_address_unique unique (wallet_address),
  constraint users_telegram_user_id_unique unique (telegram_user_id),
  constraint users_tier_check check (
    tier = any (array['bronze'::text, 'silver'::text, 'gold'::text, 'platinum'::text, 'diamond'::text])
  ),
  constraint users_identity_check check (
    telegram_user_id is not null or wallet_address is not null
  )
) TABLESPACE pg_default;

-- Projects table
create table public.projects (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  title text not null,
  summary text null,
  telegram_message_id bigint null,
  telegram_chat_id bigint null,
  user_id bigint null,
  status text null default 'in_review'::text,
  feedback_summary text null,
  constraint projects_pkey primary key (id),
  constraint projects_user_id_fkey foreign KEY (user_id) references users (id),
  constraint projects_status_check check (
    (
      status = any (array['in_review'::text, 'active'::text, 'archived'::text])
    )
  )
) TABLESPACE pg_default;

create index IF not exists projects_telegram_message_id_idx on public.projects using btree (telegram_message_id) TABLESPACE pg_default;

create index IF not exists projects_user_id_idx on public.projects using btree (user_id) TABLESPACE pg_default;

-- Feedback table
create table public.feedback (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  project_id bigint null,
  user_id bigint null,
  content text null,
  message_id bigint not null,
  parent_message_id bigint null,
  media_url text null,
  media_type text null,
  score_relevance integer null,
  score_depth integer null,
  score_evidence integer null,
  score_constructiveness integer null,
  score_tone integer null,
  score_originality integer null,
  content_embedding vector(1536),
  constraint feedback_pkey primary key (id),
  constraint feedback_project_id_fkey foreign KEY (project_id) references projects (id) on delete CASCADE,
  constraint feedback_user_id_fkey foreign KEY (user_id) references users (id)
) TABLESPACE pg_default;

-- Project Attachments table
create table public.project_attachments (
  id bigint generated by default as identity not null,
  project_id bigint not null,
  url text not null,
  media_type text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint project_attachments_pkey primary key (id),
  constraint project_attachments_project_id_fkey foreign key (project_id) references projects (id) on delete cascade
) TABLESPACE pg_default;

create index if not exists project_attachments_project_id_idx on public.project_attachments using btree (project_id) TABLESPACE pg_default;

create index IF not exists feedback_project_id_idx on public.feedback using btree (project_id) TABLESPACE pg_default;

create index IF not exists feedback_user_id_idx on public.feedback using btree (user_id) TABLESPACE pg_default;

-- Index for vector similarity search using cosine distance
create index IF not exists feedback_content_embedding_idx on public.feedback using ivfflat (content_embedding vector_cosine_ops) with (lists = 100);

-- Whitelist table for admin wallets
create table public.whitelist (
  id bigint generated by default as identity not null,
  wallet_address text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint whitelist_pkey primary key (id),
  constraint whitelist_wallet_address_unique unique (wallet_address)
) TABLESPACE pg_default;

create index IF not exists whitelist_wallet_address_idx on public.whitelist using btree (wallet_address) TABLESPACE pg_default;