-- Add 'in_review' status to projects table
-- Update the status check constraint to include 'in_review'
ALTER TABLE public.projects 
DROP CONSTRAINT IF EXISTS projects_status_check;

ALTER TABLE public.projects 
ADD CONSTRAINT projects_status_check 
CHECK (status = ANY (ARRAY['in_review'::text, 'active'::text, 'archived'::text]));

-- Update the default status for new projects
ALTER TABLE public.projects 
ALTER COLUMN status SET DEFAULT 'in_review'::text;

-- Create whitelist table for admin wallets
CREATE TABLE IF NOT EXISTS public.whitelist (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  wallet_address text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT whitelist_pkey PRIMARY KEY (id),
  CONSTRAINT whitelist_wallet_address_unique UNIQUE (wallet_address)
) TABLESPACE pg_default;

-- Create index on wallet_address for faster lookups
CREATE INDEX IF NOT EXISTS whitelist_wallet_address_idx 
ON public.whitelist USING btree (wallet_address) TABLESPACE pg_default;

-- Insert example whitelist entries (replace with actual wallet addresses)
-- INSERT INTO public.whitelist (wallet_address) VALUES ('0x1234567890abcdef1234567890abcdef12345678');

